services:
  dbt:
    container_name: dbt
    build:
      context: . # This is directory of Dockerfile location
      dockerfile: dbt.Dockerfile # This is prefered `Dockerfile` in case of multiple build exist
    # command: ["dbt", "--version"]
    # command: [ "/bin/bash" ]
    # command: build
    tty: true
    environment:
    # PODMAN_xxx is custom variable to staging between .env and profiles.yml of dbt
      - PODMAN_DBT_USER=${OMOP_PG_USER}
      - TRINO_EXPOSE_PORT=${TRINO_EXPOSE_PORT}
      ## Only for early development, Trino itself require NO PASSWORD (doesn't mean not require, or any password) to be access
      # - PODMAN_DBT_PASSWORD=${OMOP_PG_PW}
    restart: always
    volumes: 
      - ./src/pipelines:/usr/app # Your sub-module should named `dbt` inside `pipelines` directory
      - ./src/dwh/dbt/profiles.yml:/root/.dbt/profiles.yml
    networks:
      - omop-cloudbuild

  

networks:
  omop-cloudbuild:
    external: true
    name: omop-cloudbuild # Needed for Continuous integration