version: 2

sources:
  - name: synthea
    database: synthea
    schema: native
    tables:
      - name: patients
      - name: encounters
      - name: providers
      - name: conditions
      - name: allergies
      - name: observations
      - name: procedures
      - name: devices
      - name: medications
      - name: immunizations

  - name: cdm
    database: vocab # To change vocab db target, create new Trino catalog or change connection setting on `catalog/vocab.properties`
    schema: vocab
    tables:
      - name: concept
      - name: vocabulary
      - name: concept_ancestor
      - name: concept_relationship
      - name: relationship
      - name: concept_synonym
      - name: domain
      - name: concept_class
      - name: drug_strength
      - name: source_to_concept_map