version: '3'

services:
  rstudio-server:
    container_name: rstudio-server
    build:
      context: compose/.
      dockerfile: R-ohdsi.Dockerfile
    ports:
      - 8787:8787
      - 6311:6311
    volumes:
      - ./rstudio/home:/home
      - ./rstudio/tmp:/tmp
    environment:
      # - USER=rstudio
      - PASSWORD=${RSERVER_PW}
      # - ROOT=TRUE
    networks:
      - omop-cloudbuild



networks:
  omop-cloudbuild:
    external: true
    name: omop-cloudbuild # Needed for Continuous integration