version: '3'

services:
  ohdsi-atlas:
    container_name: ohdsi-atlas
    image: ohdsi/atlas:2.13.0
    ports:
      - 8081:8080
    environment:
      WEBAPI_HOST: ${BROADSEA_HOST}
      WEBAPI_URL: ${BROADSEA_HOST}/WebAPI
      ATLAS_INSTANCE_NAME: ${ATLAS_INSTANCE_NAME}
      ATLAS_COHORT_COMPARISON_RESULTS_ENABLED: ${ATLAS_COHORT_COMPARISON_RESULTS_ENABLED}
      ATLAS_USER_AUTH_ENABLED: ${ATLAS_USER_AUTH_ENABLED}
      ATLAS_PLP_RESULTS_ENABLED: ${ATLAS_PLP_RESULTS_ENABLED}
      ATLAS_SECURITY_PROVIDER_NAME: ${ATLAS_SECURITY_PROVIDER_NAME}
      ATLAS_SECURITY_PROVIDER_TYPE: ${ATLAS_SECURITY_PROVIDER_TYPE}
      ATLAS_SECURITY_ICON: ${ATLAS_SECURITY_ICON}
      ATLAS_SECURITY_USE_FORM: ${ATLAS_SECURITY_USE_FORM}
      ATLAS_SECURITY_USE_AJAX: ${ATLAS_SECURITY_USE_AJAX}
    volumes:
      - ./atlas/config-local.js:/tmp/config-local.js:ro
      - ./atlas/envsubst.sh:/tmp/envsubst.sh:ro
    entrypoint: ["sh", "/tmp/envsubst.sh" ]
    networks:
      - omop-cloudbuild

networks:
  omop-cloudbuild:
    external: true
    name: omop-cloudbuild # Needed for Continuous integration